Add daily runner
NYCPlanning/db-safegraph pull request #49
Opened 2020-10-15 19:12 UTC by mgraber

2020-10-15 19:29 UTC, SPTKL requested changes

2020-10-15 19:29 UTC, SPTKL commented on .github/workflows/daily.yml
> +      - name: install dependencies ...
we just need to do `pip3 install -r requirements.txt` here

2020-10-15 19:29 UTC, SPTKL commented on .github/workflows/daily.yml
> +        working-directory: recipes
we need to remove working directory for all, the file `./sg` is in root

2020-10-15 19:29 UTC, SPTKL commented on .github/workflows/daily.yml
> +    - cron: 0 0 * * *
should we run this slightly after we run `sync`? like 1 hour after?

2020-10-15 19:56 UTC, mgraber commented
I am currently running the historical quarters. We need to switch to the current quarter method in the py scripts before merging.

Maybe we can keep historical quarter version in another branch.

2020-10-16 12:52 UTC, SPTKL approved these changes

2020-10-16 12:52 UTC, merged